"""empty message

Revision ID: e513945b7ec1
Revises: 
Create Date: 2023-12-27 19:40:54.122429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e513945b7ec1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('g_auth_verify', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('contact',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plant',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('common_name', sa.String(length=250), nullable=False),
    sa.Column('scientific_name', sa.String(length=250), nullable=False),
    sa.Column('days_to_harvest', sa.String(length=50), nullable=True),
    sa.Column('sowing', sa.String(length=300), nullable=True),
    sa.Column('light', sa.String(length=300), nullable=True),
    sa.Column('row_spacing', sa.String(length=50), nullable=True),
    sa.Column('minimum_root_depth', sa.String(length=50), nullable=True),
    sa.Column('soil_nutriments', sa.String(length=300), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant')
    op.drop_table('contact')
    op.drop_table('user')
    # ### end Alembic commands ###
